apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-boar-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: blue-boar-container
          image: jackng971111/red_boar
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: demoApp
