apiVersion: apps/v1
kind: Deployment
metadata:
  name: boar-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: boar-container
          image: jackng971111/blue_boar
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: demoApp
